Repository SOPT-all/35-APPJAM-WEB-CAKEY, pull requests merged in 2025-03, with the labels that each got.

#233 [Feat/#232] 모달 버튼 사이즈 변경
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
Labels: ✨ feature, 😽 지유

#234 [Feat/#227] 지하철 역 검색 기능 추가
  public/svg/ic_search.svg
  public/svg/ic_x_circle.svg
  src/assets/svgs/IcSearch.tsx
  src/assets/svgs/IcXCircle.tsx
  src/assets/svgs/index.ts
  src/components/common/Input/Input.css.ts
  src/components/common/Input/Input.tsx
  src/pages/view/components/LocationButton/LocationButton.css.ts
  src/pages/view/components/LocationButton/LocationButton.tsx
  src/pages/view/components/LocationSelectButton/LocationSelectButton.css.ts
  src/pages/view/components/LocationSelectButton/LocationSelectButton.tsx
  src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
  src/pages/view/components/SelectStationModal/SelectStationModal.tsx
Labels: ✨ feature, 🥨 채연

#235 [Feat/#229] 지도뷰 모달 flow 수정 및 지도뷰 선택 디자인 조회 api 요청
  src/apis/view/index.ts
  src/apis/view/useFetchCakeInfo.ts
  src/components/common/CardList/CardList.tsx
  src/components/common/DesignCard/DesignCard.tsx
  src/components/common/StoreCard/StoreCard.tsx
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
  src/pages/view/hooks/useKakaoMap.tsx
  src/types/apis/view/index.ts
Labels: 🐛 fix, ✨ feature, 👻 화랑

#236 [Feat/#231] 홈 레이아웃 변경, 이미지 최적화 도전
  public/svg/ic_click_cta.svg
  src/assets/svgs/IcClickCta.tsx
  src/assets/svgs/index.ts
  src/pages/home/page/HomePage/HomePage.css.ts
  src/pages/home/page/HomePage/HomePage.tsx
Labels: ✨ feature, 😽 지유
