Repository SOPT-all/35-APPJAM-WEB-CAKEY, pull requests merged in 2025-01, with the labels that each got.

#2 [Init/#1] 초기세팅 (react+vite+typescript / eslint, prettier)
  .gitignore
  .prettierrc
  eslint.config.js
  index.html
  package.json
  public/vite.svg
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ⚙️setting, 🎬init

#4 [Init/#3] 폴더구조 세팅
  src/apis/.keep
  src/assets/images/.keep
  src/components/common/index.ts
  src/constants/.keep
  src/hooks/index.ts
  src/pages/.keep
  src/routes/.keep
  src/styles/.keep
  src/types/.keep
  src/utils/.keep
Labels: ⚙️setting, 🎬init, 👻화랑

#9 [Init/#6] path alias 설정
  package.json
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, 🥨채연

#16 [Deploy/#15] CI/CD Github Actions 배포 준비 완료
  .github/workflows/auto-sync.yml
Labels: ⛳deploy, 👻화랑

#7 [Init/#5] SVGR 세팅
  custom.d.ts
  package-lock.json
  package.json
  public/svg/.keep
  src/assets/svgs/.keep
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, ☘️서연

#19 [Fix/#18] yarn.lock 충돌 해결
  package-lock.json
  yarn.lock
Labels: 🐛fix, ☘️서연

#17 [Init/#10] reset, global, theme 등 style 관련 세팅
  package.json
  src/App.tsx
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  src/styles/theme.css.ts
  vite.config.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, 🥨채연

#14 [Init/#11] tanstack-query, axios 초기 세팅
  .gitignore
  package.json
  src/App.tsx
  src/apis/api.ts
  src/queryClient.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, 👻화랑

#21 [Init/#13] router 초기 세팅
  package.json
  src/App.tsx
  src/pages/auth/page/LoginPage/LoginPage.css.ts
  src/pages/auth/page/LoginPage/LoginPage.tsx
  src/pages/auth/page/index.ts
  src/pages/designList/page/DesignListPage/DesignListPage.css.ts
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/pages/designList/page/index.ts
  src/pages/home/page/HomePage/HomePage.css.ts
  src/pages/home/page/HomePage/HomePage.tsx
  src/pages/home/page/index.ts
  src/pages/myPage/page/Mypage/MyPage.css.ts
  src/pages/myPage/page/Mypage/MyPage.tsx
  src/pages/myPage/page/index.ts
  src/pages/store/page/StorePage/StorePage.css.ts
  src/pages/store/page/StorePage/StorePage.tsx
  src/pages/store/page/index.ts
  src/pages/view/page/ViewPage/ViewPage.css.ts
  src/pages/view/page/ViewPage/ViewPage.tsx
  src/pages/view/page/index.ts
  src/routes/authRoutes.tsx
  src/routes/designListRoutes.tsx
  src/routes/homeRoutes.tsx
  src/routes/index.ts
  src/routes/myPageRoutes.tsx
  src/routes/routePath.ts
  src/routes/storeRoutes.tsx
  src/routes/viewRoutes.tsx
  src/types/index.ts
  src/types/routeType.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, 😽지유

#23 [Init/#8] Storybook 세팅 및 자동 배포 설정
  .github/workflows/storybook.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.css
  src/stories/Button.stories.ts
  src/stories/Colors.stories.tsx
  src/stories/Configure.mdx
  src/stories/Typography.stories.tsx
  yarn.lock
Labels: ⛳deploy, ⚙️setting, 🎬init, ☘️서연

#24 [Init/#22] import문 정렬 및 eslint 세팅
  eslint.config.js
  package.json
  src/App.tsx
  src/components/common/index.ts
  src/main.tsx
  src/routes/authRoutes.tsx
  src/routes/designListRoutes.tsx
  src/routes/homeRoutes.tsx
  src/routes/index.ts
  src/routes/myPageRoutes.tsx
  src/routes/storeRoutes.tsx
  src/routes/viewRoutes.tsx
  src/stories/Button.stories.ts
  src/styles/global.css.ts
  src/styles/reset.css.ts
  yarn.lock
Labels: ⚙️setting, 🎬init, 🥨채연

#26 [Docs#25] 리드미 내용 추가
  README.md
Labels: 🎬init, 🥨채연

#35 [Feat/#30] SocialLoginButton 컴포넌트 구현
  package.json
  public/svg/.keep
  public/svg/ic_kakao.svg
  src/assets/svgs/.keep
  src/assets/svgs/IcKakao.tsx
  src/assets/svgs/index.ts
  src/components/common/SocialLoginButton/SocialLoginButton.css.ts
  src/components/common/SocialLoginButton/SocialLoginButton.tsx
  src/components/common/index.ts
  src/pages/auth/page/LoginPage/LoginPage.tsx
  src/stories/SocialLoginButton.stories.ts
  src/styles/.keep
  src/styles/generator.css.ts
  src/styles/theme.css.ts
  tsconfig.app.json
  yarn.lock
Labels: ✨feature, 👻화랑

#42 [Fix/#41] theme파일 font-weight, line-height 수정
  src/styles/theme.css.ts
Labels: 🐛fix, 👻화랑

#50 [Fix/#49] 디자인 시스템 변경에 따른 Theme 수정
  index.html
  src/components/common/SocialLoginButton/SocialLoginButton.css.ts
  src/hooks/useEasyNavigate.ts
  src/styles/global.css.ts
  src/styles/theme.css.ts
Labels: 🐛fix, 🥨채연

#34 [Feat/#27] Label 컴포넌트 구현
  src/components/common/Label/Label.tsx
  src/components/common/Label/label.css.ts
  src/components/common/index.ts
Labels: ✨feature, 😽지유

#46 [Feat/#39] tab componants 구현
  src/App.tsx
  src/components/common/Tab/Tab.css.ts
  src/components/common/Tab/Tab.tsx
  src/components/common/index.ts
Labels: ✨feature, 😽지유

#48 [Feat/#32] textbutton 컴포넌트 구현
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.css
  src/components/common/TextButton/TextButton.css.ts
  src/components/common/TextButton/TextButton.tsx
  src/components/common/index.ts
  src/stories/Button.stories.ts
  src/stories/TextButton.stories.ts
Labels: ✨feature, 🥨채연

#51 [Feat/#43] Header 컴포넌트 구현
  public/svg/ic_my.svg
  public/svg/img_logo.svg
  src/assets/svgs/IcMy.tsx
  src/assets/svgs/ImgLogo.tsx
  src/assets/svgs/index.ts
  src/components/common/Header/Header.css.ts
  src/components/common/Header/Header.tsx
  src/components/common/index.ts
  src/stories/Header.stories.ts
  src/styles/generator.css.ts
Labels: ✨feature, ☘️서연

#54 [Feat/#36] CenterModal 컴포넌트 구현
  index.html
  src/components/common/CenterModal/CenterModal.css.ts
  src/components/common/CenterModal/CenterModal.tsx
  src/components/common/index.ts
  src/hooks/useModal.ts
Labels: ✨feature, 🥨채연

#56 [Feat#55] BottomModal 공통 컴포넌트 구현
  src/components/common/BottomModal/BottomModal.css.ts
  src/components/common/BottomModal/BottomModal.tsx
  src/components/common/index.ts
  src/hooks/useModal.ts
Labels: ✨feature, 🥨채연

#57 [Feat/#44] Storybook 디자인 시스템 반영 및 전역 스타일 설정
  .github/workflows/storybook.yml
  .storybook/preview.ts
  src/stories/Colors.stories.tsx
  src/stories/Configure.mdx
  src/stories/Typography.stories.tsx
Labels: ✨feature, ☘️서연

#58 [Feat/#53] FilteringButton 공통 컴포넌트 구현
  public/svg/ic_arrow_down_20.svg
  public/svg/ic_arrow_up_20.svg
  src/assets/svgs/IcArrowDown20.tsx
  src/assets/svgs/IcArrowUp20.tsx
  src/assets/svgs/index.ts
  src/components/common/FilteringButton/FilteringButton.css.ts
  src/components/common/FilteringButton/FilteringButton.tsx
  src/components/common/index.ts
Labels: ✨feature, 👻화랑

#52 [Feat/#40] IconButton 공통 컴포넌트 구현
  public/svg/ic_gpsmarker_off.svg
  public/svg/ic_gpsmarker_on.svg
  public/svg/ic_line_like_off_20.svg
  public/svg/ic_line_like_on_20.svg
  public/svg/ic_saved_off_24.svg
  public/svg/ic_saved_on_24.svg
  src/assets/svgs/IcGpsmarkerOff.tsx
  src/assets/svgs/IcGpsmarkerOn.tsx
  src/assets/svgs/IcLineLikeOff20.tsx
  src/assets/svgs/IcLineLikeOn20.tsx
  src/assets/svgs/IcSavedOff24.tsx
  src/assets/svgs/IcSavedOn24.tsx
  src/assets/svgs/index.ts
  src/components/common/IconButton/IconButton.css.ts
  src/components/common/IconButton/IconButton.tsx
  src/components/common/index.ts
  src/pages/home/page/HomePage/HomePage.tsx
Labels: ✨feature, 👻화랑

#65 [Fix/#63] like아이콘 20px일때와 36px일때 구분
  public/svg/ic_fill_like_off_36.svg
  public/svg/ic_fill_like_on_36.svg
  src/assets/svgs/IcFillLikeOff36.tsx
  src/assets/svgs/IcFillLikeOn36.tsx
  src/assets/svgs/index.ts
  src/components/common/IconButton/IconButton.css.ts
  src/components/common/IconButton/IconButton.tsx
Labels: 🐛fix, 👻화랑

#64 [Feat#31] Image 공통 컴포넌트 구현
  public/example-img.png
  src/components/common/Image/Image.css.ts
  src/components/common/Image/Image.tsx
  src/components/common/index.ts
Labels: ✨feature, 🥨채연

#70 [Fix/#66] Image컴포넌트에서 클릭 영역 수정
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Image/Image.css.ts
  src/components/common/Image/Image.tsx
Labels: 🐛fix, 👻화랑

#76 [Feat/#73] LocationSelectButton 컴포넌트 구현 완료
  public/svg/ic_check.svg
  src/assets/svgs/IcCheck.tsx
  src/assets/svgs/index.ts
  src/pages/view/components/LocationSelectButton/LocationSelectButton.css.ts
  src/pages/view/components/LocationSelectButton/LocationSelectButton.tsx
  src/pages/view/components/index.ts
Labels: ✨feature, 👻화랑

#74 [Feat/#69] DesignCard 컴포넌트 구현
  src/components/common/DesignCard/DesignCard.css.ts
  src/components/common/DesignCard/DesignCard.tsx
  src/types/index.ts
  src/types/types.ts
Labels: ✨feature, 🥨채연

#67 [Feat/#61] Modal 컴포넌트 구현
  src/components/common/BottomModal/BottomModal.css.ts
  src/components/common/CenterModal/CenterModal.css.ts
  src/components/common/CenterModal/CenterModal.tsx
  src/components/common/Modal/Modal.css.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/index.ts
Labels: ✨feature, 🥨채연

#59 [Feat/#33] BottomSheet 컴포넌트 구현
  package.json
  src/components/common/BottomSheet/BottomSheet.css.ts
  src/components/common/BottomSheet/BottomSheet.tsx
  yarn.lock
Labels: ✨feature, ☘️서연

#72 [Feat/#71] LocationButton 컴포넌트 구현 완료
  public/svg/ic_arrow_right_24.svg
  public/svg/ic_location.svg
  src/assets/svgs/IcArrowRight24.tsx
  src/assets/svgs/IcLocation.tsx
  src/assets/svgs/index.ts
  src/pages/view/components/LocationButton/LocationButton.css.ts
  src/pages/view/components/LocationButton/LocationButton.tsx
  src/pages/view/components/index.ts
Labels: ✨feature, 👻화랑

#77 [Feat/#62] StoreCard 컴포넌트 구현
  src/components/common/Image/Image.css.ts
  src/components/common/StoreCard/StoreCard.css.ts
  src/components/common/StoreCard/StoreCard.tsx
  src/components/common/index.ts
  src/types/types.ts
Labels: ✨feature, 😽지유

#78 [Feat/#75] Carousel 컴포넌트 구현
  public/svg/ic_ circle_arrow_right_42.svg
  src/assets/svgs/IcCircleArrowRight42.tsx
  src/assets/svgs/index.ts
  src/pages/designList/components/Carousel.css.ts
  src/pages/designList/components/Carousel.tsx
Labels: ✨feature, 🥨채연

#80 [Fix/#79] store tab 컴포넌트 상하 padding 값 수정
  src/components/common/Tab/Tab.css.ts
Labels: 🐛fix, 😽지유

#84 [Feat/#82] SubCategoryBar 컴포넌트 구현
  src/constants/categoryData.ts
  src/constants/index.ts
  src/pages/designList/components/SubCategoryBar/SubCategoryBar.css.ts
  src/pages/designList/components/SubCategoryBar/SubCategoryBar.tsx
Labels: ✨feature, 🥨채연

#87 [Feat/#81] LetsGoButton 컴포넌트 구현
  public/svg/ic_arrow_right_24.svg
  public/svg/ic_mypage_arrow_right_24.svg
  src/assets/svgs/IcMypageArrowRight24.tsx
  src/assets/svgs/index.ts
  src/pages/myPage/components/LetsGoButton/LetsGoButton.css.ts
  src/pages/myPage/components/LetsGoButton/LetsGoButton.tsx
  src/pages/myPage/components/index.ts
Labels: ✨feature, 😽지유

#90 [Fix/#88] IconButton 컴포넌트 수정
  src/components/common/DesignCard/DesignCard.tsx
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Image/Image.tsx
  src/components/common/StoreCard/StoreCard.tsx
  src/components/common/index.ts
  src/types/types.ts
Labels: 🐛fix, 👻화랑

#93 [Feat/#83] ProfileCard 컴포넌트 구현
  public/svg/img_mypage_profile_login.svg
  src/assets/svgs/ImgMypageProfileLogin.tsx
  src/assets/svgs/index.ts
  src/pages/myPage/components/ProfileCard/ProfileCard.css.ts
  src/pages/myPage/components/ProfileCard/ProfileCard.tsx
  src/pages/myPage/components/index.ts
Labels: ✨feature, 😽지유

#89 [Feat/#68] SizeCard 컴포넌트 구현
  public/svg/img_store_11cm.svg
  public/svg/img_store_13cm.svg
  public/svg/img_store_16cm.svg
  public/svg/img_store_19cm.svg
  public/svg/img_store_22cm.svg
  src/assets/svgs/ImgStore11Cm.tsx
  src/assets/svgs/ImgStore13Cm.tsx
  src/assets/svgs/ImgStore16Cm.tsx
  src/assets/svgs/ImgStore19Cm.tsx
  src/assets/svgs/ImgStore22Cm.tsx
  src/assets/svgs/index.ts
  src/constants/.keep
  src/constants/index.ts
  src/constants/size.tsx
  src/pages/store/components/Chip/Chip.css.ts
  src/pages/store/components/Chip/Chip.tsx
  src/pages/store/components/SizeCard/SizeCard.css.ts
  src/pages/store/components/SizeCard/SizeCard.tsx
  src/pages/store/components/SizeCardList/SizeCardList.css.ts
  src/pages/store/components/SizeCardList/SizeCardList.tsx
Labels: ✨feature, ☘️서연

#94 [Feat/#45] Toast 컴포넌트 및 useToast 구현
  .storybook/preview-body.html
  index.html
  public/svg/ic_toast_check.svg
  public/svg/ic_toast_error.svg
  src/App.tsx
  src/assets/svgs/IcToastCheck.tsx
  src/assets/svgs/IcToastError.tsx
  src/assets/svgs/index.ts
  src/components/common/Toast/Toast.css.ts
  src/components/common/Toast/Toast.tsx
  src/components/common/index.ts
  src/contexts/ToastContext.tsx
  src/contexts/index.ts
  src/stories/Toast.stories.ts
  src/styles/generator.css.ts
  src/types/index.ts
  src/types/toastType.ts
  tsconfig.app.json
Labels: ✨feature, ☘️서연

#92 [Feat/#86] CardList 컴포넌트 구현
  src/components/common/CardList/CardList.css.ts
  src/components/common/CardList/CardList.tsx
  src/components/common/DesignCard/DesignCard.tsx
  src/components/common/FilteringButton/FilteringButton.css.ts
  src/components/common/FilteringButton/FilteringButton.tsx
  src/components/common/Image/Image.css.ts
  src/components/common/StoreCard/StoreCard.css.ts
  src/components/common/StoreCard/StoreCard.tsx
  src/components/common/index.ts
  src/types/types.ts
Labels: 🐛fix, ✨feature, 👻화랑, 🥨채연

#101 [Feat/#99] Layout 설정
  src/App.tsx
  src/routes/.keep
  src/routes/Layout/Layout.css.ts
  src/routes/Layout/Layout.tsx
  src/routes/index.ts
  src/routes/pageRoutes.tsx
Labels: ✨feature, ☘️서연

#102 [Feat/#95] CategoryButton 컴포넌트 구현
  eslint.config.js
  package.json
  public/svg/ic_search_category_aniv_unactivate.svg
  public/svg/ic_search_category_bday_unactivate.svg
  public/svg/ic_search_category_cheer_unactivate.svg
  public/svg/ic_search_category_season_unactivate.svg
  src/App.tsx
  src/assets/lotties/btn_search_category_aniv_activate.json
  src/assets/lotties/btn_search_category_bday_activate.json
  src/assets/lotties/btn_search_category_cheer_activate.json
  src/assets/lotties/btn_search_category_season_activate.json
  src/assets/lotties/index.ts
  src/assets/svgs/IcSearchCategoryAnivUnactivate.tsx
  src/assets/svgs/IcSearchCategoryBdayUnactivate.tsx
  src/assets/svgs/IcSearchCategoryCheerUnactivate.tsx
  src/assets/svgs/IcSearchCategorySeasonUnactivate.tsx
  src/assets/svgs/index.ts
  src/constants/category.tsx
  src/constants/categoryData.ts
  src/constants/index.ts
  src/pages/designList/components/Carousel/Carousel.css.ts
  src/pages/designList/components/Carousel/Carousel.tsx
  src/pages/designList/components/CategoryBar/CategoryBar.css.ts
  src/pages/designList/components/CategoryBar/CategoryBar.tsx
  src/pages/designList/components/CategoryButton/CategoryButton.css.ts
  src/pages/designList/components/CategoryButton/CategoryButton.tsx
  src/pages/designList/components/SubCategoryBar/SubCategoryBar.tsx
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/types/types.ts
  tsconfig.app.json
  yarn.lock
Labels: ✨feature, 🥨채연

#104 [Feat/#100] AuthModal 컴포넌트 구현
  src/components/common/AuthModal/AuthModal.css.ts
  src/components/common/AuthModal/AuthModal.tsx
  src/components/common/TextButton/TextButton.css.ts
  src/components/common/index.ts
Labels: ✨feature, 😽지유

#96 [Feat/#91] SelectStationModal 컴포넌트 구현
  src/components/common/BottomSheet/BottomSheet.css.ts
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/Header/Header.css.ts
  src/components/common/Header/Header.tsx
  src/components/common/Toast/Toast.css.ts
  src/components/common/Toast/Toast.tsx
  src/constants/category.tsx
  src/contexts/ToastContext.tsx
  src/hooks/index.ts
  src/pages/myPage/components/index.ts
  src/pages/store/components/SizeCard/SizeCard.css.ts
  src/pages/store/components/SizeCard/SizeCard.tsx
  src/pages/store/components/SizeCardList/SizeCardList.tsx
  src/pages/view/components/LocationButton/LocationButton.css.ts
  src/pages/view/components/LocationButton/LocationButton.tsx
  src/pages/view/components/LocationSelectButton/LocationSelectButton.css.ts
  src/pages/view/components/LocationSelectButton/LocationSelectButton.tsx
  src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
  src/pages/view/components/SelectStationModal/SelectStationModal.tsx
  src/pages/view/components/index.ts
  src/pages/view/page/ViewPage/ViewPage.tsx
  src/routes/Layout/Layout.tsx
  src/routes/index.ts
  src/routes/pageRoutes.tsx
  src/stories/Header.stories.ts
  src/stories/Toast.stories.ts
  src/styles/global.css.ts
  src/styles/theme.css.ts
Labels: ✨feature, 👻화랑

#106 [Fix/#105] Layout 대소문자 오류 해결
  src/routes/pageRoutes.tsx
Labels: 🐛fix, ☘️서연

#108 [Fix/#107] 라우트 import문 순서 에러 수정
  eslint.config.js
  src/pages/error/Error.css.ts
  src/pages/error/Error.tsx
  src/pages/error/index.ts
  src/routes/index.ts
  src/routes/routePath.ts
  src/routes/storeRoutes.tsx
Labels: 🐛fix, 👻화랑

#109 [Feat/#103] DesignSearchModal 컴포넌트 구현
  src/components/common/DesignCard/DesignCard.css.ts
  src/pages/designList/components/Carousel/Carousel.css.ts
  src/pages/designList/components/Carousel/Carousel.tsx
  src/pages/designList/components/DesignSearchModal/DesignSearchModal.css.ts
  src/pages/designList/components/DesignSearchModal/DesignSearchModal.tsx
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/types/types.ts
Labels: ✨feature, 🥨채연

#38 [Feat/#37] Input 컴포넌트 구현
  public/svg/ic_arrow_right_24.svg
  public/svg/ic_form_dot.svg
  public/svg/ic_form_dotdot.svg
  src/App.tsx
  src/assets/svgs/IcFormDot.tsx
  src/assets/svgs/IcFormDotdot.tsx
  src/assets/svgs/index.ts
  src/components/common/Input/Input.css.ts
  src/components/common/Input/Input.tsx
  src/components/common/index.ts
  src/stories/Input.stories.tsx
Labels: ✨feature, 😽지유

#117 [Feat/#116] StoreRankingButton 컴포넌트 구현
  public/svg/ic_arrow_right_20.svg
  src/assets/svgs/IcArrowRight20.tsx
  src/assets/svgs/index.ts
  src/pages/home/components/StoreRankingButton/StoreRankingButton.css.ts
  src/pages/home/components/StoreRankingButton/StoreRankingButton.tsx
  src/pages/home/components/index.ts
Labels: ✨feature, 😽지유

#113 [Feat/#98] Mypage 뷰 퍼블리싱
  src/App.tsx
  src/components/common/Tab/Tab.css.ts
  src/hooks/useEasyNavigate.ts
  src/pages/myPage/components/LetsGoButton/LetsGoButton.css.ts
  src/pages/myPage/components/index.ts
  src/pages/myPage/page/MyList/MyList.css.ts
  src/pages/myPage/page/MyList/MyList.tsx
  src/pages/myPage/page/Mypage/MyPage.css.ts
  src/pages/myPage/page/Mypage/MyPage.tsx
  src/pages/myPage/page/index.ts
  src/routes/index.ts
Labels: ✨feature, 😽지유

#111 [Feat/#97] 스토어 상세보기 페이지 퍼블리싱
  public/svg/ic_line_location.svg
  public/svg/ic_phone.svg
  public/svg/ic_store_location.svg
  public/svg/ic_time.svg
  src/assets/svgs/IcLineLocation.tsx
  src/assets/svgs/IcPhone.tsx
  src/assets/svgs/IcStoreLocation.tsx
  src/assets/svgs/IcTime.tsx
  src/assets/svgs/index.ts
  src/components/common/IconButton/IconButton.css.ts
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Image/Image.css.ts
  src/components/common/StoreCard/StoreCard.tsx
  src/components/common/Tab/Tab.css.ts
  src/components/common/Tab/Tab.tsx
  src/components/common/TextButton/TextButton.css.ts
  src/components/common/TextButton/TextButton.tsx
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/pages/store/components/Banner/Banner.css.ts
  src/pages/store/components/Banner/Banner.tsx
  src/pages/store/components/BottomTab/BottomTab.css.ts
  src/pages/store/components/BottomTab/BottomTab.tsx
  src/pages/store/components/OrderGuideButton/OrderGuideButton.css.ts
  src/pages/store/components/OrderGuideButton/OrderGuideButton.tsx
  src/pages/store/components/SizeCardList/SizeCardList.tsx
  src/pages/store/components/StoreDesign/StoreDesign.css.ts
  src/pages/store/components/StoreDesign/StoreDesign.tsx
  src/pages/store/components/StoreInfo/StoreInfo.css.ts
  src/pages/store/components/StoreInfo/StoreInfo.tsx
  src/pages/store/components/StoreMenu/StoreMenu.css.ts
  src/pages/store/components/StoreMenu/StoreMenu.tsx
  src/pages/store/page/StorePage/StorePage.css.ts
  src/pages/store/page/StorePage/StorePage.tsx
  src/pages/store/page/StorePage/storeData.ts
  src/pages/view/components/SelectStationModal/SelectStationModal.tsx
  src/routes/index.ts
  src/stories/TextButton.stories.ts
  src/styles/global.css.ts
  src/types/types.ts
  src/utils/.keep
  src/utils/formatHours.ts
  src/utils/index.ts
Labels: ✨feature, ☘️서연

#120 [Feat/#60] KakaoMap 컴포넌트 구현
  package.json
  public/image/ic_location_my.png
  public/image/ic_store_default_32.png
  public/image/ic_store_default_54.png
  public/image/ic_store_like_32.png
  public/image/ic_store_like_54.png
  src/assets/images/.keep
  src/constants/images/index.ts
  src/constants/index.ts
  src/constants/stations.tsx
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/KakaoMap/kakaoMap.css.ts
  src/pages/view/components/MapButton/MapButton.css.ts
  src/pages/view/components/MapButton/MapButton.tsx
  src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
  src/pages/view/components/SelectStationModal/SelectStationModal.tsx
  src/pages/view/components/index.ts
  src/pages/view/hooks/index.ts
  src/pages/view/hooks/useDebounce.tsx
  src/pages/view/hooks/useKakaoMap.tsx
  src/pages/view/hooks/useMapLoader.tsx
  src/pages/view/page/ViewPage/ViewPage.tsx
  src/types/types.ts
  src/utils/getMarkerIcon.ts
  src/utils/index.ts
  yarn.lock
Labels: ✨feature, 👻화랑

#114 [Feat/#110] 둘러보기 페이지 퍼블리싱
  src/components/common/CardList/CardList.css.ts
  src/components/common/CardList/CardList.tsx
  src/components/common/DesignCard/DesignCard.tsx
  src/components/common/FilteringButton/FilteringButton.tsx
  src/hooks/useFilteredCardList.ts
  src/pages/designList/components/CategoryButton/CategoryButton.tsx
  src/pages/designList/components/DesignSearchModal/DesignSearchModal.tsx
  src/pages/designList/components/SubCategoryBar/SubCategoryBar.tsx
  src/pages/designList/page/DesignListPage/DesignListPage.css.ts
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/types/types.ts
Labels: ✨feature, 🥨채연

#124 [Feat/#123] 이미지 전체보기 모달 구현
  public/svg/ic_x.svg
  src/assets/svgs/IcX.tsx
  src/assets/svgs/index.ts
  src/pages/store/components/ImageModal/ImageModal.css.ts
  src/pages/store/components/ImageModal/ImageModal.tsx
  src/pages/store/components/StoreDesign/StoreDesign.tsx
  src/routes/index.ts
Labels: ✨feature, ☘️서연

#119 [Feat/#112] 주문서 양식 모달 구현
  public/svg/ic_form_x_20.svg
  src/assets/svgs/IcFormX20.tsx
  src/assets/svgs/index.ts
  src/components/common/Input/Input.css.ts
  src/components/common/Input/Input.tsx
  src/components/common/TextButton/TextButton.css.ts
  src/components/common/TextButton/TextButton.tsx
  src/constants/index.ts
  src/constants/order.ts
  src/hooks/index.ts
  src/hooks/useClipboard.ts
  src/pages/store/components/BottomTab/BottomTab.tsx
  src/pages/store/components/OrderFormModal/OrderFormModal.css.ts
  src/pages/store/components/OrderFormModal/OrderFormModal.tsx
  src/pages/store/components/OrderGuideButton/OrderGuideButton.css.ts
  src/pages/store/components/OrderGuideButton/OrderGuideButton.tsx
  src/pages/store/components/StoreInfo/StoreInfo.css.ts
  src/pages/store/components/StoreInfo/StoreInfo.tsx
  src/pages/store/page/StorePage/StorePage.tsx
  src/pages/store/page/StorePage/storeData.ts
  src/stories/Input.stories.tsx
  src/styles/global.css.ts
  src/types/index.ts
  src/types/orderFormType.ts
Labels: ✨feature, ☘️서연

#122 [Feat/#121] Login Page 구현
  public/image/loginPageImage.png
  src/constants/images/index.ts
  src/pages/auth/page/LoginPage/LoginPage.css.ts
  src/pages/auth/page/LoginPage/LoginPage.tsx
Labels: ✨feature, 😽지유

#130 [Feat/#128] 파비콘 설정 및 스크롤 설정
  eslint.config.js
  index.html
  public/svg/img_favicon.svg
  src/constants/category.tsx
  src/hooks/useScrollTop.ts
  src/routes/Layout/Layout.tsx
Labels: ✨feature, 🥨채연

#129 [Feat/#126] 마이페이지 페이지 연결 구현
  src/components/common/AuthModal/AuthModal.tsx
  src/constants/index.ts
  src/constants/url.tsx
  src/hooks/useEasyNavigate.ts
  src/hooks/useFilteredCardList.ts
  src/pages/auth/page/LoginPage/LoginPage.tsx
  src/pages/myPage/page/MyList/LikeListPage.css.ts
  src/pages/myPage/page/MyList/LikeListPage.tsx
  src/pages/myPage/page/MyList/MyList.tsx
  src/pages/myPage/page/Mypage/MyPage.tsx
  src/pages/myPage/page/index.ts
  src/routes/myPageRoutes.tsx
  src/routes/routePath.ts
Labels: ✨feature, 😽지유

#131 [Feat/#125] ViewPage 컴포넌트 퍼블리싱
  src/components/common/BottomSheet/BottomSheet.tsx
  src/hooks/index.ts
  src/hooks/useBottomSheet.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/hooks/useKakaoMap.tsx
  src/pages/view/page/ViewPage/ViewPage.css.ts
  src/pages/view/page/ViewPage/ViewPage.tsx
  src/types/types.ts
Labels: ✨feature, 👻화랑

#132 [Feat/#127] 지도 바텀시트 컴포넌트 구현
  src/components/common/BottomSheet/BottomSheet.css.ts
  src/components/common/StoreCard/StoreCard.css.ts
  src/components/common/Tab/Tab.css.ts
  src/hooks/index.ts
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/pages/view/components/MapBottomSheet/MapBottomSheet.css.ts
  src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
Labels: ✨feature, ☘️서연

#134 [Fix/#133] MapBottomSheet 수정
  src/hooks/index.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
  src/stories/Input.stories.tsx
Labels: 🐛fix, 👻화랑

#136 [Deploy/#135] vercel.json 추가
  vercel.json
Labels: ⛳deploy, 👻화랑

#141 [Setting/#137] TanStack Query 세팅
  index.html
  package.json
  src/apis/auth/.keep
  src/apis/designList/.keep
  src/apis/error/.keep
  src/apis/home/useFetchStoreRank.ts
  src/apis/instance.ts
  src/apis/myPage/.keep
  src/apis/store/.keep
  src/apis/view/.keep
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/constants/index.ts
  src/types/apis/auth/index.ts
  src/types/apis/commonType.ts
  src/types/apis/designList/index.ts
  src/types/apis/error/index.ts
  src/types/apis/home/index.ts
  src/types/apis/myPage/index.ts
  src/types/apis/store/index.ts
  src/types/apis/view/index.ts
  src/types/index.ts
  yarn.lock
Labels: ⚙️setting, ☘️서연

#145 [Feat/#138] 카카오로그인 구현 완료
  src/apis/auth/.keep
  src/apis/auth/usePostKakaoLogin.ts
  src/apis/instance.ts
  src/components/common/SocialLoginButton/SocialLoginButton.tsx
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/main.tsx
  src/pages/auth/page/LoginPage/LoginPage.tsx
  src/pages/auth/page/Redirection/Redirection.tsx
  src/pages/auth/page/index.ts
  src/routes/authRoutes.tsx
  src/routes/routePath.ts
  src/types/apis/auth/index.ts
  src/types/apis/commonType.ts
  src/types/index.ts
  src/utils/auth.ts
  src/utils/index.ts
Labels: ✨feature, 👻화랑

#146 [Feat/#143] 스토어 좌표 리스트 조회 API 연결
  src/apis/view/useFetchStoreCoordinateList.ts
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/constants/stations.tsx
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/hooks/useKakaoMap.tsx
  src/types/apis/view/index.ts
  src/types/types.ts
Labels: ✨feature, 👻화랑

#148 [Feat/#140] 인기 케이크 조회 API 연결
  src/apis/home/index.ts
  src/apis/home/useFetchCakeRank.ts
  src/apis/home/useFetchStoreRank.ts
  src/apis/instance.ts
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/home/page/HomePage/HomePage.tsx
  src/types/apis/home/index.ts
Labels: ✨feature, 😽지유

#157 [Feat/#152] 지도 뷰 선택 스토어 모달 구현
  src/components/common/Modal/Modal.css.ts
  src/pages/store/components/ImageModal/ImageModal.css.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.css.ts
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
Labels: ✨feature, ☘️서연

#155 [Feat/#151] 사용자 정보(이름, 이메일) 조회 API 연결
  src/apis/myPage/.keep
  src/apis/myPage/index.ts
  src/apis/myPage/useFetchUser.ts
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/home/page/HomePage/HomePage.tsx
  src/pages/myPage/page/Mypage/MyPage.tsx
  src/types/apis/myPage/index.ts
Labels: ✨feature, 😽지유

#163 [Fix/#162] IconButton 스타일 및 onMap속성 수정
  src/components/common/IconButton/IconButton.css.ts
  src/components/common/IconButton/IconButton.tsx
Labels: 🐛fix, 👻화랑

#159 [Feat/#156] 스토어 찜하기 API 연결
  src/apis/likes/index.ts
  src/apis/likes/usePostStoreLikes.ts
  src/components/common/IconButton/IconButton.tsx
  src/constants/apis/api.ts
  src/pages/store/components/Banner/Banner.tsx
  src/types/apis/commonType.ts
Labels: ✨feature, 😽지유

#164 [Feat/#160] 케이크 디자인 좋아요 하기 API 연결
  src/apis/likes/index.ts
  src/apis/likes/usePostCakeLikes.ts
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Image/Image.tsx
  src/constants/apis/api.ts
  src/pages/store/components/StoreDesign/StoreDesign.tsx
Labels: ✨feature, 😽지유

#150 [Feat/#142] 스토어 상세보기 페이지 조회 API 연결
  src/apis/store/.keep
  src/apis/store/index.ts
  src/apis/store/useFetchStoreDetailDesign.ts
  src/apis/store/useFetchStoreDetailInfo.ts
  src/apis/store/useFetchStoreDetailSize.ts
  src/apis/store/useFetchStoreInfo.ts
  src/apis/store/useFetchStoreLink.ts
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/store/components/BottomTab/BottomTab.tsx
  src/pages/store/components/SizeCardList/SizeCardList.tsx
  src/pages/store/components/StoreDesign/StoreDesign.tsx
  src/pages/store/components/StoreInfo/StoreInfo.tsx
  src/pages/store/components/StoreMenu/StoreMenu.tsx
  src/pages/store/page/StorePage/StorePage.tsx
  src/pages/store/page/StorePage/storeData.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
  src/types/apis/store/index.ts
  src/utils/formatHours.ts
Labels: ✨feature, ☘️서연

#168 [Feat/#161] 선택 스토어 좌표 조회 API 연결
  src/apis/store/index.ts
  src/apis/store/useFetchSelectStoreCoordinate.ts
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/store/components/BottomTab/BottomTab.tsx
  src/pages/view/hooks/useKakaoMap.tsx
Labels: ✨feature, 👻화랑

#172 [Fix/#171] 둘러보기 페이지 API 오류 해결
  src/apis/designList/useFetchDesignDetail.ts
  src/apis/designList/useFetchDesignList.ts
  src/apis/store/useFetchStoreInfo.ts
  src/components/common/CardList/CardList.tsx
  src/components/common/DesignCard/DesignCard.tsx
  src/components/common/FilteringButton/FilteringButton.tsx
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/hooks/useFilteredCardList.ts
  src/pages/designList/components/Carousel/Carousel.css.ts
  src/pages/designList/components/DesignSearchModal/DesignSearchModal.tsx
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/pages/home/components/CategoryCard/CategoryCard.tsx
  src/pages/myPage/page/MyList/LikeListPage.tsx
Labels: 🐛fix, 🥨채연

#174 [Feat/#149] 마이페이지 찜 목록 스토어 및 디자인 like API 연결
  src/apis/instance.ts
  src/apis/likes/useDeleteCakeLikes.ts
  src/apis/likes/useDeleteStoreLikes.ts
  src/apis/likes/usePostCakeLikes.ts
  src/apis/likes/usePostStoreLikes.ts
  src/apis/myPage/index.ts
  src/apis/myPage/useFetchLikedCakeList.ts
  src/components/common/StoreCard/StoreCard.tsx
  src/constants/apis/api.ts
  src/constants/apis/queryKey.ts
  src/pages/myPage/page/MyList/LikeListPage.tsx
  src/types/apis/myPage/index.ts
Labels: ✨feature, 😽지유

#176 [Feat/#175] 로그아웃 API 연결
  src/apis/auth/index.ts
  src/apis/auth/useDeleteLogout.ts
  src/apis/designList/useFetchDesignList.ts
  src/apis/myPage/useFetchLikedCakeList.ts
  src/apis/myPage/useFetchLikedStoreList.ts
  src/apis/myPage/useFetchUser.ts
  src/apis/view/useFetchLikesStoreCoordinate.ts
  src/assets/lotties/index.ts
  src/assets/lotties/loading.json
  src/components/common/AuthModal/AuthModal.tsx
  src/constants/apis/api.ts
  src/pages/error/index.ts
  src/pages/status/Error/Error.css.ts
  src/pages/status/Error/Error.tsx
  src/pages/status/Loading/Loading.css.ts
  src/pages/status/Loading/Loading.tsx
  src/pages/status/index.ts
  src/routes/storeRoutes.tsx
  src/types/apis/commonType.ts
  src/utils/auth.ts
Labels: ✨feature, 👻화랑

#183 [Fix] 스토어 정보 리스트 조회 enabled 조건문 수정
  src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
Labels: 🐛fix, ☘️서연

#185 [Feat/#181] Axios interceptor 404 에러 처리 및 스토어 상세보기 관련 API 반영
  src/apis/designList/useFetchDesignList.ts
  src/apis/instance.ts
  src/apis/myPage/useFetchLikedCakeList.ts
  src/apis/myPage/useFetchLikedStoreList.ts
  src/apis/store/useFetchSelectStoreCoordinate.ts
  src/apis/store/useFetchStoreDetailDesign.ts
  src/apis/store/useFetchStoreDetailInfo.ts
  src/apis/store/useFetchStoreDetailSize.ts
  src/apis/store/useFetchStoreInfo.ts
  src/apis/store/useFetchStoreLink.ts
  src/pages/store/components/BottomTab/BottomTab.tsx
  src/pages/store/components/StoreInfo/StoreInfo.tsx
  src/pages/view/components/KakaoMap/KakaoMap.tsx
Labels: ✨feature, ☘️서연

#191 [Feat/#144] Footer 만들기
  public/svg/ic_footer_logo.svg
  src/assets/svgs/IcFooterLogo.tsx
  src/assets/svgs/ImgFavicon.tsx
  src/assets/svgs/index.ts
  src/components/common/Footer/Footer.css.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/index.ts
  src/pages/home/page/HomePage/HomePage.tsx
  src/pages/myPage/page/Mypage/MyPage.css.ts
  src/pages/myPage/page/Mypage/MyPage.tsx
  src/styles/global.css.ts
Labels: ✨feature, 🥨채연

#186 [Feat/#177] 토스트 띄우기
  src/apis/likes/useDeleteCakeLikes.ts
  src/apis/likes/useDeleteStoreLikes.ts
  src/apis/likes/usePostCakeLikes.ts
  src/apis/likes/usePostStoreLikes.ts
  src/components/common/Toast/Toast.tsx
  src/contexts/ToastContext.tsx
  src/pages/myPage/page/MyList/LikeListPage.tsx
  src/types/toastType.ts
Labels: ✨feature, 😽지유

#188 [Feat/#184] 로그인 없이 필요한 기능 실행 시 로그인 모달 띄우기
  src/components/common/AuthModal/AuthModal.tsx
  src/components/common/IconButton/IconButton.tsx
  src/hooks/useEasyNavigate.ts
  src/pages/auth/page/LoginPage/LoginPage.css.ts
  src/pages/auth/page/LoginPage/LoginPage.tsx
  src/types/apis/commonType.ts
Labels: ✨feature, 👻화랑

#192 [Feat/#187] 리스트 조회 API 404 에러 기본값 설정
  src/apis/designList/useFetchDesignList.ts
  src/apis/myPage/useFetchLikedCakeList.ts
  src/apis/myPage/useFetchLikedStoreList.ts
  src/apis/view/useFetchLikedStoreDesign.ts
  src/apis/view/useFetchLikesStoreCoordinate.ts
  src/apis/view/useFetchStationDesign.ts
  src/apis/view/useFetchStationStore.ts
  src/apis/view/useFetchStations.ts
  src/apis/view/useFetchStoreCoordinateList.ts
Labels: ✨feature, ☘️서연

#196 [Fix/#189] ViewPage 리펙토링
  src/components/common/BottomSheet/BottomSheet.css.ts
  src/components/common/StoreCard/StoreCard.css.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/KakaoMap/kakaoMap.css.ts
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛fix, 👻화랑

#197 [Fix/#195] 메인페이지 누락된 '전체보기' 버튼 추가
  public/svg/ic_arrow_right_16.svg
  src/assets/svgs/IcArrowRight16.tsx
  src/assets/svgs/index.ts
  src/pages/home/page/HomePage/HomePage.css.ts
  src/pages/home/page/HomePage/HomePage.tsx
Labels: ✨feature, 🥨채연

#198 [Fix/#194] 지도 뷰 퍼블리싱 오류 수정
  src/components/common/BottomSheet/BottomSheet.css.ts
  src/pages/view/components/MapBottomSheet/MapBottomSheet.css.ts
  src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
  src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
Labels: 🐛fix, ☘️서연

#200 [Feat/#199] 인기 스토어 / 케이크 조회 404 에러 처리
  src/apis/home/useFetchCakeRank.ts
  src/apis/home/useFetchStoreRank.ts
  src/apis/instance.ts
  src/apis/myPage/useFetchUser.ts
  src/pages/store/components/Banner/Banner.tsx
  src/pages/store/components/StoreMenu/StoreMenu.css.ts
  src/types/apis/store/index.ts
Labels: ✨feature, ☘️서연

#204 [Fix/#203] 웹파트 내부 QA 3차 수정
  src/apis/auth/useDeleteLogout.ts
  src/apis/myPage/useFetchUser.ts
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.css.ts
  src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛 fix, 👻 화랑

#209 [Feat/#207] Tab 인터랙션 구현
  src/components/common/Tab/Tab.css.ts
  src/components/common/Tab/Tab.tsx
Labels: 🎨 design, ✨ feature, ☘️ 서연

#212 [Fix/#211] 로그인 로직 수정
  src/apis/auth/useDeleteLogout.ts
  src/apis/auth/usePostKakaoLogin.ts
  src/apis/instance.ts
  src/types/apis/auth/index.ts
  src/utils/auth.ts
Labels: 🐛 fix, ☘️ 서연

#215 [Fix/#208] 지도뷰 수정
  src/apis/auth/usePostKakaoLogin.ts
  src/apis/myPage/useFetchUser.ts
  src/apis/view/useFetchLikesStoreCoordinate.ts
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Image/Image.css.ts
  src/pages/home/page/HomePage/HomePage.tsx
  src/pages/view/components/KakaoMap/KakaoMap.tsx
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛 fix, 👻 화랑, 🥨 채연

#216 [Feat/#213] TopButton 구현
  public/svg/ic_top.svg
  src/assets/svgs/IcTop.tsx
  src/assets/svgs/index.ts
  src/components/common/TextButton/TextButton.tsx
  src/components/common/TopButton/TopButton.css.ts
  src/components/common/TopButton/TopButton.tsx
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useScrollTop.ts
  src/pages/designList/page/DesignListPage/DesignListPage.tsx
  src/pages/myPage/page/MyList/LikeListPage.tsx
  src/routes/Layout/Layout.tsx
Labels: ✨ feature, ☘️ 서연

#218 [Fix/#217] 지하철 역 선택 모달 스타일 수정
  src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
Labels: 🐛 fix, 🎨 design, ☘️ 서연

#222 [Fix/#220] 찜 개수 변경 시 마커 반영 안되는 에러 해결
  src/apis/likes/useDeleteStoreLikes.ts
  src/apis/likes/usePostStoreLikes.ts
  src/apis/view/useFetchLikesStoreCoordinate.ts
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛 fix, ☘️ 서연

#221 [Fix/#219] 기획 & 디자인 QA 1차 수정
  src/components/common/Toast/Toast.css.ts
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛 fix, 👻 화랑

#225 [Fix/#224] 지도뷰 모달 수정
  src/pages/view/hooks/useKakaoMap.tsx
Labels: 🐛 fix, 👻 화랑
